blank_issues_enabled: false

contact_links:
  - name: ğŸ“–  Read the docs
    url:  https://miskler.github.io/jsonschema-diff/basic/quick_start/
    about: Start here for â€œhow-toâ€ questions.
  - name: ğŸ’¬  Discord server (Discussions)
    url:  https://discord.gg/UnJnGHNbBp
    about: General Q&A and community support.
